language: python
python:
    - 3.6
# command to install dependencies
install: 
    - pip install pipenv
    - pipenv install --dev --three

# # command to run tests
script: 
    - pipenv shell
    - pipenv run python manage.py test